'use client';
import { useState } from 'react';
import { AppLayout } from '@/components/AppLayout';
import { api } from '@/lib/api';

export default function SettingsPage() {
  const [clearing, setClearing] = useState(false);
  const [clearMsg, setClearMsg] = useState<{ ok: boolean; text: string } | null>(null);

  async function handleClearDb() {
    if (!confirm('⚠️ This will permanently delete live transactions but preserve the ML training dataset. Continue?')) return;
    setClearing(true);
    setClearMsg(null);
    try {
      await api.request('DELETE', '/payments/admin/reset-data');
      setClearMsg({ ok: true, text: 'Live transactions cleared successfully. ML training data was preserved.' });
    } catch (e: any) {
      setClearMsg({ ok: false, text: e.message ?? 'Failed to clear database.' });
    } finally {
      setClearing(false);
    }
  }

  return (
    <AppLayout title="Settings">
      <div className="page-header">
        <div>
          <div className="page-title">Settings</div>
          <div className="page-desc">System configuration and preferences</div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, maxWidth: 900 }}>
        {[
          { title: 'API Connection', fields: [
            { label: 'Backend URL', value: process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:8000', type: 'text' },
          ]},
          { title: 'Risk Thresholds', fields: [
            { label: 'Block Threshold (score)', value: '85', type: 'number' },
            { label: 'Review Threshold (score)', value: '50', type: 'number' },
          ]},
          { title: 'AI Investigator', fields: [
            { label: 'Gemini API Key', value: '••••••••••••••••', type: 'password' },
            { label: 'Model', value: 'gemini-2.5-flash', type: 'text' },
          ]},
          { title: 'Display', fields: [
            { label: 'Default Page Size', value: '20', type: 'number' },
            { label: 'Timezone', value: 'UTC', type: 'text' },
          ]},
        ].map(section => (
          <div key={section.title} className="card">
            <div className="card-header"><div className="card-title">{section.title}</div></div>
            <div className="card-body">
              {section.fields.map(f => (
                <div key={f.label} className="detail-field" style={{ marginBottom: 16 }}>
                  <div className="detail-label">{f.label}</div>
                  <input
                    type={f.type}
                    defaultValue={f.value}
                    style={{
                      marginTop: 4,
                      width: '100%',
                      padding: '7px 10px',
                      border: '1px solid var(--color-border-md)',
                      borderRadius: 'var(--radius-md)',
                      fontFamily: 'var(--font-sans)',
                      fontSize: 13,
                      color: 'var(--color-text)',
                      background: 'var(--color-surface)',
                      outline: 'none',
                    }}
                  />
                </div>
              ))}
              <button className="btn btn-secondary" style={{ marginTop: 4 }}>Save Changes</button>
            </div>
          </div>
        ))}

        {/* Danger Zone */}
        <div className="card" style={{ borderTop: '2px solid #b91c1c', gridColumn: '1 / -1' }}>
          <div className="card-header" style={{ background: '#fef2f2' }}>
            <div>
              <div className="card-title" style={{ color: '#b91c1c' }}>Danger Zone</div>
              <div className="card-subtitle">Irreversible operations — proceed with caution</div>
            </div>
          </div>
          <div className="card-body">
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 24 }}>
              <div>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--color-text)', marginBottom: 4 }}>
                  Clear Database
                </div>
                <div style={{ fontSize: 12, color: 'var(--color-text-2)', maxWidth: 480 }}>
                  Permanently deletes all live transactions generated by the gateway. 
                  The 50,000-transaction ML training dataset, model weights, and system schema are completely preserved.
                  This is safe to run to clear noise without affecting model accuracy.
                </div>
                {clearMsg && (
                  <div style={{
                    marginTop: 10,
                    padding: '8px 12px',
                    fontSize: 12,
                    borderRadius: 'var(--radius-sm)',
                    background: clearMsg.ok ? 'var(--color-low-bg)' : 'var(--color-critical-bg)',
                    color: clearMsg.ok ? 'var(--color-low)' : 'var(--color-critical)',
                    border: `1px solid ${clearMsg.ok ? 'var(--color-low-border)' : 'var(--color-critical-border)'}`,
                  }}>
                    {clearMsg.text}
                  </div>
                )}
              </div>
              <button
                id="btn-clear-db"
                className="btn"
                disabled={clearing}
                onClick={handleClearDb}
                style={{
                  flexShrink: 0,
                  background: clearing ? '#e5e7eb' : '#b91c1c',
                  color: clearing ? 'var(--color-text-2)' : 'white',
                  border: 'none',
                  cursor: clearing ? 'not-allowed' : 'pointer',
                  opacity: clearing ? 0.7 : 1,
                  fontWeight: 600,
                  minWidth: 130,
                }}
              >
                {clearing ? 'Clearing…' : '🗑 Clear Database'}
              </button>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  );
}
