"""Update RiskEvaluation model

Revision ID: 1905bc12c54a
Revises: 937d0872c55e
Create Date: 2026-09-03 23:02:44.641449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1905bc12c54a'
down_revision: Union[str, Sequence[str], None] = '937d0872c55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_evaluations', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('risk_evaluations', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_evaluations', 'signals')
    op.drop_column('risk_evaluations', 'decision')
    # ### end Alembic commands ###
