"""Add ground_truth table

Revision ID: 937d0872c55e
Revises: dd4ce4988c0e
Create Date: 2026-09-03 22:48:00.052998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d0872c55e'
down_revision: Union[str, Sequence[str], None] = 'dd4ce4988c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_truth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('fraud_scenario', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_truth_label'), 'ground_truth', ['label'], unique=False)
    op.create_index(op.f('ix_ground_truth_transaction_id'), 'ground_truth', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ground_truth_transaction_id'), table_name='ground_truth')
    op.drop_index(op.f('ix_ground_truth_label'), table_name='ground_truth')
    op.drop_table('ground_truth')
    # ### end Alembic commands ###
